# Generated by Django 3.2.1 on 2024-02-12 16:55

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Divisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('akronim', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jabatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kompetensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OpenSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipePertanyaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('NPM', models.IntegerField(unique=True)),
                ('divisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.divisi')),
                ('jabatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.jabatan')),
                ('tipe_pertanyaan', models.ManyToManyField(to='main.TipePertanyaan')),
            ],
        ),
        migrations.CreateModel(
            name='Pertanyaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertanyaan', models.TextField()),
                ('jenis_pertanyaan', models.CharField(choices=[('LIKERT', 'Likert'), ('TEXT', 'Text')], default='LIKERT', max_length=10)),
                ('kompetensi_pertanyaan', smart_selects.db_fields.ChainedForeignKey(chained_field='tipe_pertanyaan', chained_model_field='tipe_pertanyaan', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.kompetensi')),
                ('tipe_pertanyaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tipepertanyaan')),
            ],
        ),
        migrations.CreateModel(
            name='Penilaian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(blank=True, null=True, verbose_name='Jawaban')),
                ('done', models.BooleanField(default=False, editable=False)),
                ('id_dinilai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinilai', to='main.user', verbose_name='Nama Dinilai')),
                ('id_penilai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilai', to='main.user', verbose_name='Nama Penilai')),
            ],
        ),
        migrations.AddField(
            model_name='kompetensi',
            name='tipe_pertanyaan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tipepertanyaan'),
        ),
    ]
