# Generated by Django 3.2.1 on 2024-02-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='NPM',
            field=models.BigIntegerField(unique=True),
        ),
    ]
